# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FaceBookLoginReview' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FaceBookLoginReview
  pod 'FacebookCore', :git => 'https://github.com/facebook/facebook-sdk-swift'
  pod 'FacebookLogin', :git => 'https://github.com/facebook/facebook-sdk-swift'
  pod 'FacebookShare', :git => 'https://github.com/facebook/facebook-sdk-swift'

end
