//
//  CreateOrderWorker.swift
//  CleanStore
//
//  Created by Paul Sevilla on 26/05/2016.
//  Copyright (c) 2016 Paul Sevilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class CreateOrderWorker
{
  // MARK: Business Logic
  
  func doSomeWork()
  {
    // NOTE: Do the work
  }
}
