# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MultipleStoryboards' do
pod 'RBStoryboardLink', '~> 0.1'
pod 'ECSlidingViewController', '~> 2.0'
pod 'SDWebImage', '~> 3.7'
end

target 'MultipleStoryboardsTests' do

end

